version: '3.8'
services:
  backend:
    build:
      context: backend/server/
      target: service
    ports:
      - "8090:8090"
  frontend:
    build:
      context: frontend/react-app/
    environment:
      - REACT_APP_BACKEND_HOST=http://localhost:8090
    ports:
      - "3000:3000"
