version: '3.8'
services:
  backend:
    build:
      context: backend/server/
      target: service
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend/react-app/
    environment:
      - REACT_APP_BACKEND_HOST="http://backend:8090"
    ports:
      - "3000:3000"
