version: '3.8'
services:
  backend:
    build:
      context: backend/server/
      target: service
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend/react-app/
    ports:
      - "3000:3000"
