#!/bin/bash

java -DapiTests=false -jar backend/openapi-generator/openapi-generator-cli.jar generate -g python-fastapi -i ./api/TViewer-api.yaml -o backend/server -p packageName=TViewer,generatorLanguageVersion=3.11 -t backend/openapi-generator/template