openapi: 3.0.3
info:
  title: Swagger TViewer
  description: |-
    This is a REST backend server for TViewer based on the OpenAPI 3.0 specification. 
    
    Some useful links:
    - [Design file](https://drive.google.com/file/d/1u6ViGBnWCJq9aX6OlfR6dLi6wmErJ4da/view?usp=share_link)
    
  version: 0.0.1

# servers:
#   - url: https://petstore3.swagger.io/api/v3

tags:
  - name: Profiles
    description: Everything about our profiles

paths:
  /profiles:
    get:
      tags:
        - Profiles
      summary: Get profile names
      description: Get all active trader profiles
      operationId: getProfiles
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profiles'
  /profiles/{name}/configuration/:
    get:
      tags: 
        - Profiles
      summary: Get profile configuration
      description: Get details of trading configuration
      parameters:
        - in: path
          name: name   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            example: "Denis"
          description: The user name
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
  /profiles/{name}/historical-data/:
    get:
      tags: 
        - Profiles
      summary: Get data for candlesticks
      description: Get **historical data** in format of candlesticks with particular **timeframe** 
      parameters:
        - in: path
          name: name   # Note the name is the same as in the path
          required: true
          schema:
            type: string
            example: "Denis"
          description: The user name
        - in: query
          name: timeframe
          required: true
          schema:
            type: integer
            example: 60
          description: Amount of seconds for candlesticks interval
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoricalData'              
    
          
components:
  schemas:
    Profiles:
      type: array
      items:
        type: string
      example: ["Denis", "Daniil", "KVF"]
      uniqueItems: true
    Configuration:
      required:
        - name
        - configuration
      type: object
      properties:
        start-time:
          type: string
          format: date-time
        configuration:  # TODO
          type: object
    HistoricalData:
      type: array
      items:
        type: object
        required:
          - time
          - open
          - high
          - low
          - close
        properties:
          time:
            type: string
            format: date-time
          open:
            type: number
            format: float
            example: 100.5
          high:
            type: number
            format: float
            example: 110.0
          low:
            type: number
            format: float
            example: 98.5
          close:
            type: number
            format: float
            example: 102
            
            
            
            
            
  