#FROM python:{{{generatorLanguageVersion}}} AS builder
FROM python:3.11 AS builder

WORKDIR /usr/src/app

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip install --upgrade pip

COPY . .
RUN pip install --no-cache-dir .


#FROM python:{{{generatorLanguageVersion}}} AS test_runner
FROM python:3.11 AS test_runner
WORKDIR /tmp
COPY --from=builder /venv /venv
COPY --from=builder /usr/src/app/tests tests
ENV PATH=/venv/bin:$PATH

#ENV PYTHONPATH=$(pwd)+/src:$PYTHONPATH

# install test dependencies
# RUN pip install -r tests/test_requirements.txt
# RUN pip install pytest

# run tests
# RUN pytest tests


#FROM python:{{generatorLanguageVersion}} AS service
FROM python:3.11 AS service
WORKDIR /venv/lib/python{{generatorLanguageVersion}}/site-packages/TViewer
COPY --from=builder /venv /venv
ENV PATH=/venv/bin:$PATH
CMD {{packageName}}
